#
- name: Open port 24007 (GlusterFS daemon)
  firewalld: port=24007/tcp zone="{{ default_zone.stdout }}" permanent=true state=enabled immediate=true
#  shell: firewall-cmd --permanent --zone="{{ default_zone.stdout }}" --add-port=24007/tcp
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: Open port 24008 (GlusterFS management)
  firewalld: port=24008/tcp zone="{{ default_zone.stdout }}" permanent=true state=enabled immediate=true
#  shell: firewall-cmd --permanent --zone="{{ default_zone.stdout }}" --add-port=24008/tcp
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: Open port 2222 (GlusterFS sshd)
  firewalld: port=2222/tcp zone="{{ default_zone.stdout }}" permanent=true state=enabled immediate=true
#  shell: firewall-cmd --permanent --zone="{{ default_zone.stdout }}" --add-port=2222/tcp
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: Open ports 49152-49251 (GlusterFS bricks)
  firewalld: port=49152-49251/tcp zone="{{ default_zone.stdout }}" permanent=true state=enabled immediate=true
#  shell: firewall-cmd --permanent --zone="{{ default_zone.stdout }}" --add-port=49152-49251/tcp
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: Pull GlusterFS Docker image
  command: docker pull gluster/gluster-centos:latest
  register: task_result
  until: task_result.rc == 0
  retries: 5
  delay: 1

- name: Pull heketi Docker image
  command: docker pull heketi/heketi:dev
  register: task_result
  until: task_result.rc == 0
  retries: 5
  delay: 1
