- name: build hosts file
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_eth1.ipv4.address }} {{item}}" state=present
  when: hostvars[item].ansible_eth1.ipv4.address is defined
  with_items: "{{ groups['all'] }}"

- name: disable selinux
  selinux: state=disabled

- name: disable of selinux - now
  command: setenforce 0
  ignore_errors: yes

- name: install base packages
  yum: state=present update_cache=yes pkg={{ install_pkgs }}
  retries: 5
  delay: 1

- name: firewalld - enable eth1
  firewalld: zone="{{ default_zone.stdout }}" interface=eth1 permanent=true state=enabled immediate=true
#  shell: firewall-cmd --permanent --zone="{{ default_zone.stdout }}" --add-interface=eth1
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: firewalld - enable CIDR source 172.30.0.0/16
  firewalld: source=172.30.0.0/16 zone="{{ default_zone.stdout }}" permanent=true state=enabled immediate=true
#  shell: firewall-cmd --permanent --zone="{{ default_zone.stdout }}" --add-source=172.30.0.0/16
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

# 10.32.0.0/12 is the default pod CIDR for Weave Net
# you will need to update this if you are using a different
# network provider, or a different CIDR for whatever reason
- name: firewalld - enable CIDR 10.128.0.0/14
  firewalld: source=10.128.0.0/14 zone="{{ default_zone.stdout }}" permanent=true state=enabled immediate=true
#  shell: firewall-cmd --permanent --zone="{{ default_zone.stdout }}" --add-source=10.128.0.0/14
  retries: 5
  delay: 5

- name: firewalld - Open Port 10250/tcp
  firewalld: port=10250/tcp zone="{{ default_zone.stdout }}" permanent=true state=enabled immediate=true
#  shell: firewall-cmd --permanent --zone="{{ default_zone.stdout }}" --add-port=10250/tcp
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: firewalld - Open Port 6443/tcp
  firewalld: port=6443/tcp zone="{{ default_zone.stdout }}" permanent=true state=enabled immediate=true
#  shell: firewall-cmd --permanent --zone="{{ default_zone.stdout }}" --add-port=9898/tcp
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: firewalld - Open Port 9898/tcp
  firewalld: port=9898/tcp zone="{{ default_zone.stdout }}" permanent=true state=enabled immediate=true
#  shell: firewall-cmd --permanent --zone="{{ default_zone.stdout }}" --add-port=9898/tcp
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: Open port 24007 (GlusterFS daemon)
  firewalld: port=24007/tcp zone="{{ default_zone.stdout }}" permanent=true state=enabled immediate=true
#  shell: firewall-cmd --permanent --zone="{{ default_zone.stdout }}" --add-port=24007/tcp
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: Open port 24008 (GlusterFS management)
  firewalld: port=24008/tcp zone="{{ default_zone.stdout }}" permanent=true state=enabled immediate=true
#  shell: firewall-cmd --permanent --zone="{{ default_zone.stdout }}" --add-port=24008/tcp
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: Open port 2222 (GlusterFS sshd)
  firewalld: port=2222/tcp zone="{{ default_zone.stdout }}" permanent=true state=enabled immediate=true
#  shell: firewall-cmd --permanent --zone="{{ default_zone.stdout }}" --add-port=2222/tcp
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: Open ports 49152-49664 (GlusterFS bricks)
  firewalld: port=49152-49664/tcp zone="{{ default_zone.stdout }}" permanent=true state=enabled immediate=true
#  shell: firewall-cmd --permanent --zone="{{ default_zone.stdout }}" --add-port=49152-49251/tcp
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: Open port 8443 
  firewalld: port=8443/tcp zone="{{ default_zone.stdout }}" permanent=true state=enabled immediate=true
#  shell: firewall-cmd --permanent --zone="{{ default_zone.stdout }}" --add-port=8443/tcp
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5

- name: Open port 4789 
  firewalld: port=4789/udp zone="{{ default_zone.stdout }}" permanent=true state=enabled immediate=true
#  shell: firewall-cmd --permanent --zone="{{ default_zone.stdout }}" --add-port=4789/udp
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5